# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package -Pdev -DskipTests --file pom.xml
    - name: upload build result
      run: mkdir staging && cp oh-my-scheduler-server/target/*.jar staging/oms-server.jar && cp oh-my-scheduler-client/target/*.jar staging/oms-client.jar && cp oh-my-scheduler-worker-agent/target/*.jar staging/oms-agent.jar
    - uses: actions/upload-artifact@v1
      with:
        name: oms-server.jar
        path: staging/oms-server.jar
    - uses: actions/upload-artifact@v1
      with:
        name: oms-client.jar
        path: staging/oms-client.jar
    - uses: actions/upload-artifact@v1
      with:
        name: oms-agent.jar
        path: staging/oms-agent.jar
